CREATE TABLE "inscription_courses" (
  "user_id" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "user_rol" (
  "user_id" int NOT NULL,
  "rol_id" int NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "password" varchar(10) NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(150) NOT NULL,
  "description" varchar(800) NOT NULL,
  "level" varchar(100) NOT NULL,
  "teacher" varchar(150) NOT NULL,
  "categorie_id" int NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(500) NOT NULL,
  "url" varchar(200) NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(150) NOT NULL
);

ALTER TABLE "inscription_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "inscription_courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "course_videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("categorie_id") REFERENCES "categories" ("id");

ALTER TABLE "user_rol" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_rol" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id");

INSERT INTO roles (name) VALUES ('Student'), ('Teacher'), ('Administrative');
 
INSERT INTO users (name, email, password, age) VALUES
('Juan Mendoza', 'juan@gmail.com', 1234, 17),
('Mirlen Marquez', 'mirlen@gmail.com', 1234, 40),
('Rosa Rivas', 'rosa@gmail.com', 1234, 40),
('Sharly Mendoza', 'sharly@gmail.com', 1234, 40);

INSERT INTO user_rol (user_id, rol_id) VALUES
(1, 1),
(2, 3),
(3, 2),
(3, 3),
(4, 2),
(4, 1);

INSERT INTO categories (name) VALUES ('Development'), ('Music');

INSERT INTO courses (title, description, level, teacher_id, category_id) VALUES
('Fundamentos', 'Start HTML CSS and JavaScript', 'Essential', 3, 1),
('Music theory', 'Minor scales, intervals, basic dictation', 'Medium', 4, 2);

INSERT INTO inscription_courses (user_id, course_id) VALUES
(1, 2),
(4, 1);

INSERT INTO course_videos (title, url, course_id) VALUES
('Introduction to HTML', 'https://www.academlo.com', 1),
('Minor Scales', 'https://www.music.com', 2);